export const actualites = [
  {
    id: 1,
    date: "15 Mars 2026",
    category: "Récolte",
    tag: "Production",
    title: "Récolte 2025-2026 : Un millésime exceptionnel pour notre Bourbon",
    excerpt:
      "La récolte de cette saison dépasse toutes nos espérances. Avec un score de cupping atteignant 87 points sur certains lots, la qualité de notre Bourbon Munanira est au sommet. Nos 276 membres ont travaillé avec une rigueur exemplaire pour sélectionner uniquement les meilleures cerises.",
    content: "Cette année, la récolte de café Bourbon à Kalehe a bénéficié de conditions climatiques optimales. Les pluies régulières et le soleil doux ont permis une maturation lente des cerises, développant ainsi des sucres complexes à l'intérieur du grain.\n\nNos 276 membres, dont 94 femmes, se sont levés tôt chaque matin pour cueillir manuellement les cerises rouges, garantissant qu'aucune cerise verte ou surmûre ne se glisse dans les lots. Le traitement à notre station de lavage communautaire a achevé de sublimer ce terroir volcanique exceptionnel, aboutissant à un café noté à 87 points par les experts en cupping.",
    image: "/images/gallery/IMG-20260323-WA0064.jpg",
    readTime: "3 min",
    author: "Fleming CIZUNGU",
    featured: true,
  },
  {
    id: 2,
    date: "8 Mars 2026",
    category: "Femmes",
    tag: "Leadership",
    title: "Journée Internationale des Femmes : COACKI célèbre ses 94 leaders",
    excerpt:
      "À l'occasion de la Journée Internationale des Femmes, COACKI rend hommage à ses 94 membres féminins qui jouent un rôle clé dans la gouvernance et la production. Leur leadership transforme le tissu social de Kalehe.",
    content: "La COACKI est fière de compter 94 femmes leaders parmi ses membres fondateurs et producteurs. Ces femmes ne sont pas seulement impliquées dans la cueillette, mais elles siègent également au comité de direction, gèrent les finances et participent activement aux décisions d'exportation.\n\nGrâce aux revenus équitables générés par la coopérative, elles peuvent réinvestir dans l'éducation de leurs enfants et l'amélioration de leurs foyers. Ce modèle inclusif démontre que le café de spécialité peut être un puissant levier d'émancipation sociale et d'indépendance financière dans le Sud-Kivu.",
    image: "/images/gallery/IMG-20260323-WA0070.jpg",
    readTime: "4 min",
    author: "Comité Femmes COACKI",
    featured: false,
  },
  {
    id: 3,
    date: "20 Février 2026",
    category: "Infrastructure",
    tag: "Station",
    title: "Extension de notre station de lavage : phase 2 commencée",
    excerpt:
      "Les travaux d'agrandissement de notre centre de traitement à Munanira ont officiellement démarré. Cette expansion financée par nos cotisations membres permettra d'augmenter notre capacité de traitement de 2,5 à 5 tonnes par jour.",
    content: "Afin de répondre à la demande croissante pour notre café de qualité supérieure, la coopérative a décidé d'investir ses fonds propres dans l'agrandissement de notre station de lavage (washing station) de Munanira.\n\nLa Phase 2 des travaux inclut la construction de deux nouveaux bassins de fermentation naturelle et l'installation de 50 lits africains supplémentaires pour le séchage au soleil. Cet ancrage local garantit que la plus-value de la transformation du café reste entièrement entre les mains des producteurs locaux.",
    image: "/images/gallery/IMG-20260323-WA0066.jpg",
    readTime: "5 min",
    author: "Direction COACKI",
    featured: false,
  },
  {
    id: 4,
    date: "5 Février 2026",
    category: "Export",
    tag: "Commerce",
    title: "Premier partenariat avec un torréfacteur européen signé",
    excerpt:
      "COACKI a officialisé un accord de fourniture exclusive avec un torréfacteur de spécialité basé à Bruxelles. Ce premier contrat d'exportation directe ouvre la voie à une reconnaissance internationale de notre Bourbon Kivu.",
    content: "C'est une étape historique pour COACKI : notre première exportation en circuit court est confirmée ! Un torréfacteur belge, impressionné par le profil aromatique floral et fruité de notre Bourbon 85+, s'engage à acheter une partie de notre production annuelle à un prix largement supérieur au marché local.\n\nCe partenariat direct élimine les intermédiaires de la chaîne de valeur, augmentant directement les revenus de nos 276 producteurs membres. Les premiers sacs en toile de jute floqués 'COACKI' quittent le port de Goma ce mois-ci.",
    image: "/images/gallery/IMG-20260323-WA0062.jpg",
    readTime: "3 min",
    author: "Fleming CIZUNGU",
    featured: false,
  },
  {
    id: 5,
    date: "18 Janvier 2026",
    category: "Formation",
    tag: "Formation",
    title: "Atelier de formation sur les bonnes pratiques de récolte",
    excerpt:
      "Vingt membres de COACKI ont participé à un atelier de 3 jours sur les techniques de sélection des cerises, la gestion du séchage et le contrôle de qualité. Ces formations continues renforcent notre engagement pour l'excellence.",
    content: "L'excellence d'un café de spécialité se joue dès l'arbre. Pour maintenir notre score de cupping de 85+, la coopérative organise régulièrement des formations pour ses membres.\n\nPendant 3 jours, nos agronomes ont formé vingt producteurs aux techniques précises de la cueillette : savoir identifier avec certitude la cerise parfaitement mûre et écarter celles atteintes par des défauts ou maladies. Le succès de ces ateliers s’observe directement à la station de lavage où les lots reçus sont de plus en plus purs.",
    image: "/images/gallery/IMG-20260323-WA0068.jpg",
    readTime: "4 min",
    author: "Comité Formation",
    featured: false,
  },
  {
    id: 6,
    date: "3 Janvier 2026",
    category: "Qualité",
    tag: "Certification",
    title: "Résultats de cupping : notre lot Munanira obtient 87 points",
    excerpt:
      "Les analyses officielles de cupping réalisées par un laboratoire indépendant confirment l'excellence de notre production. Le lot Munanira N°1 a obtenu 87 points, classant notre café parmi les meilleurs cafés de spécialité d'Afrique centrale.",
    content: "Nous avons reçu les résultats tant attendus de nos échantillons envoyés en laboratoire indépendant au Rwanda. Le lot signature 'Munanira N°1' a obtenu l'incroyable score de 87 points sur 100 sur l'échelle de la SCA (Specialty Coffee Association).\n\nLes dégustateurs ont mis en avant des flaveurs complexes de thé noir, de jasmin, de citron sucré et une acidité vibrante. C’est la meilleure récompense pour nos membres qui s'efforcent tous les jours de produire le meilleur café possible sur ces montagnes difficiles mais magnifiques du Kivu.",
    image: "/images/gallery/IMG-20260323-WA0071.jpg",
    readTime: "2 min",
    author: "Comité Qualité",
    featured: false,
  },
];
